# Generated by Django 4.1.3 on 2022-11-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_transacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.DeleteModel(
            name='Carteira',
        ),
    ]
